import { ABOUT, BLOG, CONTACT, IMPRINT, PRIVACY_POLICY, PROJECTS, STATUS } from './routes';

export const FOOTER = [STATUS, IMPRINT, PRIVACY_POLICY];

export const MAIN = [ABOUT, BLOG, PROJECTS, CONTACT];
